trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureServiceConnection: 'AzureSPN'
  appName: 'my-node-webapp'           # Azure App Service name
  packageDirectory: '.'               # Root directory of app

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build || echo "no build script"
    displayName: 'Install Dependencies & Build'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(packageDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
      replaceExistingArchive: true
    displayName: 'Archive Node App'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: $(azureServiceConnection)
      appType: 'webApp'
      appName: $(appName)
      package: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: 'Deploy to Azure Web App'
